FROM python:3.5
ENV PYTHONUNBUFFERED 1
ADD /taiga-back/requirements.txt /
RUN apt-get update && apt-get install -y gettext
RUN pip install -r /requirements.txt;

ADD /config/initial_data.sh /

WORKDIR /src