version: '2'
services:
  taigafront:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    environment:
      - TZ=America/Santiago
    volumes:
      - ./taiga-front-dist:/src
      - ./volumes/taigafront/log:/logs
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/taigaback/static:/static
      - ./volumes/taigaback/media:/media
    links:
      - taigaback
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  taigaback:
    build:
      context: .
      dockerfile: Dockerfile-back
    restart: always
    environment:
      - TZ=America/Santiago
    command: bash -c "gunicorn taiga.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./taiga-back:/src
      - ./volumes/taigaback/log:/logs
      - ./volumes/taigaback/static:/src/static
      - ./volumes/taigaback/media:/src/media
    links:
      - postgres
      - rabbitmq
    ports:
      - "9001:8000"
    expose:
      - "8000"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  taigaevents:
    build:
      context: .
      dockerfile: Dockerfile-events
    restart: always
    environment:
      - TZ=America/Santiago
    command: sh -c "/usr/local/bin/coffee index.coffee"
    volumes:
      - ./taiga-events:/src
    ports:
      - "8888:8888"
    links:
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  taigacelery:
    build:
      context: .
      dockerfile: Dockerfile-back
    restart: always
    environment:
      - TZ=America/Santiago
    command: bash -c "celery -A taiga worker -c 4 --autoscale=30,20 -l info -f logs/celery.log --loglevel=INFO"
    volumes:
      - ./taiga-back:/src
      - ./volumes/celery/log:/logs
    links:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=taigapass
      - RABBITMQ_DEFAULT_VHOST=taiga
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
      - ./volumes/rabbitmq/log:/var/log/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  postgres:
    image: postgres:9.5-alpine
    ports:
        - "5432:5432"
    volumes:
     - ./volumes/postgres:/var/lib/postgresql/data
    environment:
     - TZ=America/Santiago
     - POSTGRES_DB=taiga
     - POSTGRES_USER=taiga
     - POSTGRES_PASSWORD=taigapass
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
  redis:
    image: "redis:alpine"
    restart: always
    ports:
        - "6379:6379"
    environment:
        - TZ=America/Santiago
    volumes:
      - ./volumes/redis/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
networks:
  default:
    external:
      name: privnet
